pipeline {
  agent {
    kubernetes {
      cloud 'openshift'
      label 'maven-apps'
      defaultContainer 'jnlp'
      yamlFile 'openshift-tasks/openshiftPod.yaml'
    }
  }
  stages {
    stage('mvn') {
      steps {
        withMaven(
          maven: 'maven-3',
          mavenSettingsConfig: 'my-maven-settings') {
          sh "mvn clean version"
        }
      }
    }
  }
}      