def prefix      = "5149"
def devProject  = "${prefix}-tasks-dev"
def prodProject = "${prefix}-tasks-prod"
def devTag      = "0.0-0"
def prodTag     = "0.0"
def destApp     = "tasks-green"
def activeApp   = ""
def mvnCmd = "mvn -s openshift-tasks/nexus.xml -f openshift-tasks/pom.xml"

pipeline {
  agent {
    label "maven-appdev"
  }
  stages {
    stage('Checkout Source') {
      steps {
        checkout([$class: 'GitSCM', branches: [[name: '**']], doGenerateSubmoduleConfigurations: false, extensions: [], submoduleCfg: [], userRemoteConfigs: [[url: 'https://github.com/micaelis72/advdevtraining.git']]])    
        script {
          def pom = readMavenPom file: 'openshift-tasks/pom.xml'
          def version = pom.version

          devTag  = "${version}-" + currentBuild.number
          prodTag = "${version}"
        }
      }    
    }  
    stage('Build War File') {
      steps {
        echo "Building version ${devTag}"
        sh "${mvnCmd} clean package -DskipTests=true"
      }   
    }
    stage('Unit Tests') {
      steps {
        echo "Running Unit Tests"
        sh "${mvnCmd} test"
        step([$class: 'JUnitResultArchiver', testResults: '**/target/surefire-reports/TEST-*.xml'])
      }
    }      
  }
}