apiVersion: v1
kind: Pod
metadata:
  labels:
    name: maven-apps
spec:
  containers:
  - name: jnlp
    image: docker-registry.default.svc:5000/5149-jenkins/maven-appdev
    serviceAccount: jenkins
    resourceLimitMemory: 2Gi