apiVersion: v1
kind: Pod
metadata:
  labels:
    name: maven-apps
spec:
  containers:
  - name: jnlp
    image: docker-registry.default.svc:5000/5149-jenkins/maven-appdev
    tty: false
    serviceAccount: jenkins
    resourceLimitMemory: 2Gi
    workingDirectory: /tmp
    env:
    - name: PATH
      value: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin